projectKanpai/blog_posts/forms.py
# post view
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, RadioField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    text = TextAreaField("Text",validators=[DataRequired()])
    submit = SubmitField("post!")

projectKanpai/blog_posts/views.py
#post/view.py
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import current_user,login_required
from projectKanpai import db
from projectKanpai.models import BlogPost, User
from projectKanpai.blog_posts.forms import BlogPostForm

blog_posts = Blueprint("blog_posts", __name__)

#create
@blog_posts.route('/create', methods = ['GET', 'POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                            text=form.text.data,
                            user_id=current_user.id
                            )
        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Post Created')
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)

#blog post(view)
#as integer
# BLOG POST (VIEW)
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    print(type(blog_post))
    return render_template('blog_post.html', title=blog_post.title,
                            date=blog_post.date, post=blog_post
    )
    
#update
@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))
        
    #refill the original text
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html',title='Updating',form=form)

#delete

@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)
    # prevent permission issue 
    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted')
    return redirect(url_for('core.index'))
#like
@blog_posts.route('/<int:blog_post_id>/<action>', methods = ['GET', 'POST'])
@login_required
def like_posts(blog_post_id, action):
    user = User.query.filter_by(username = current_user.username).first_or_404()
    post = BlogPost.query.filter_by(id = blog_post_id).first()
    print(user.likePost)
    if action == "like":
        user.likePost.append(post)
        db.session.commit()
    if action == "unlike":
        user.likePost.remove(post)
        db.session.commit()
    return redirect(url_for('core.index'))

projectKanpai/core/views.py
# core/views.py
from flask import render_template, request, Blueprint
from projectKanpai.models import BlogPost, User
from projectKanpai.core.forms import SearchForm
from flask_login import current_user


core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page = page, per_page = 5)
    if current_user.is_authenticated:
        user = User.query.filter_by(username = current_user.username).first_or_404()
        likePost = user.likePost
        return render_template('index.html', blog_posts = blog_posts, likePost = likePost)
    return render_template('index.html', blog_posts = blog_posts)
    

@core.route('/search', methods = ['GET', 'POST'])
def search():
    form = SearchForm()
    if form.validate_on_submit():
        all_query = []
        key = form.key.data.split(" ")
        stopwords_array = {"i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself", "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself", "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that", "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "having", "do", "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because", "as", "until", "while", "of", "at", "by", "for", "with", "about", "against", "between", "into", "through", "during", "before", "after", "above", "below", "to", "from", "up", "down", "in", "out", "on", "off", "over", "under", "again", "further", "then", "once", "here", "there", "when", "where", "why", "how", "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so", "than", "too", "very", "s", "t", "can", "will", "just", "don", "should", "now"}
        tokens_without_sw = [word for word in key if not word in stopwords_array]
        print(tokens_without_sw)

        id = set()
        for word in tokens_without_sw:
            query1 = BlogPost.query.filter(BlogPost.title.contains(word)).all()
            print(query1)
            for ele in query1:
                if ele.id in id:
                    break
                else: 
                    id.add(ele.id) 
                all_query += [ele]
            query2 = BlogPost.query.filter(BlogPost.text.contains(word)).all()
            for ele in query2:
                print(type(ele), type(query1))
                if ele.id in id:
                    break
                else: 
                    id.add(ele.id) 
                all_query += [ele]
        print(all_query)
 
        return render_template('search.html', form = form, query = all_query)
    return render_template('search.html', form = form)

def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title=blog_post.title,
                            date=blog_post.date, post=blog_post)

projectKanpai/users/views.py
# users/views.py
from flask import render_template, redirect, request, url_for, flash, abort, Blueprint
from flask_login import login_user,login_required,logout_user, current_user
from projectKanpai import db 
# init grab db
from projectKanpai.models import User, BlogPost
from projectKanpai.users.forms import RegistrationForm, LoginForm, UpdateUserForm

#users view
users = Blueprint('users', __name__)

# register user
@users.route('/register', methods = ['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        # one second
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

 
#login user
@users.route('/login', methods = ['GET', 'POST'])
def login():
    form = LoginForm()
    a = User.query.filter_by().all()
    for i in a:
        print(i.username)
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()  
        print("--------here---------")   
        if user.check_password(form.password.data) and user is not None:
            #Log in the user

            login_user(user)
            flash('Logged in successfully.')

            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0]=='/':
                next = url_for('core.index') # to app function

            return redirect(next)
    print("not login")   
    return render_template('login.html', form=form)

#logout user
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))
#account user's list of post -- dashboard
@users.route("/account", methods = ["GET", "POST"])
@login_required
def account():
    form = UpdateUserForm()
    user = User.query.filter_by(username = current_user.username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user)
    number = len(blog_posts.all())
    # update
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', form=form, user = user, blog_posts=blog_posts, num = number)


# user's list of blog posts
@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()
    ).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

projectKanpai/templates/account.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
      <h1>Welcome to the page for {{current_user.username}}</h1>
      <p>{{ current_user.email }}</p>
  </div>

  <div class="container">
    <form method="POST">
        {{form.hidden_tag()}}
      <div class="form-group">
        {{form.username.label(class='form-group')}}
        {{form.username(class='form-control')}}
      </div>
    
      <div class="form-group">
      {{form.email.label(class='form-group')}}
      {{form.email(class='form-control')}}
      </div>

      <div class="form-group">
       {{form.submit(class='btn btn-primary')}}
      </div>
      <h3> there are {{num}} posts. </h3>
      {% if num > 0 %}
      <p>you have published <button class="btn btn-primary"> 1 </button> article</p>
      {% else %}
      <p>you have published <button class="btn btn-primary" disabled> ?? </button> article</p>
      {% endif %}

      {% if num >= 3 %}
      <p>you have published <button class="btn btn-secondary"> 3 </button> article</p>
      {% else %}
      <p>you have published <button class="btn btn-secondary" disabled> ?? </button> article</p>
      {% endif %}
      
      {% if num >= 5 %}
      <p>you have published <button class="btn btn-success"> 5 </button> article</p>
      {% else %}
      <p>you have published <button class="btn btn-success" disabled> ?? </button> article</p>
      {% endif %}
      
      {% if num >= 10 %}
      <p>you have published <button class="btn btn-danger"> 10 </button> article</p>
      {% else %}
      <p>you have published <button class="btn btn-danger" disabled> ?? </button> article</p>
      {% endif %}
      
      {% if num >= 20 %}
      <p>you have published <button class="btn btn-warning"> 10 </button> article</p>
      {% else %}
      <p>you have published <button class="btn btn-warning" disabled> ?? </button> article</p>
      {% endif %}
      
    </form>
  </div>

{% endblock %}

projectKanpai/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Kanpai</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
      <a class="navbar-brand" href="{{url_for('core.index')}}"> Home Page </a>
      <a class="navbar-brand" href="{{url_for('blog_posts.create_post')}}"> Create Post</a>
      <a class="navbar-brand" href="{{url_for('core.search')}}"> Search </a>
      
      {% if current_user.is_authenticated%}
      <a class="navbar-brand" href = "{{url_for('users.logout')}}">logout</a>
      <a class="navbar-brand" href = "{{url_for('users.account')}}">Account</a>
      {% else %}
      <a class="navbar-brand" href = "{{url_for('users.login')}}">login</a>
      <a class="navbar-brand" href = "{{url_for('users.register')}}">register</a>
      {% endif %}
    </div>
    </nav>
    {% block content %}
    {% endblock %}
  </body>
</html>

projectKanpai/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{post.title}}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{post.date.strftime('%B %d, %Y')}}</h3>
  <p>{{post.text}}</p>

  {% if post.author == current_user %}
  <div>
    <a href="{{url_for('blog_posts.update',blog_post_id=post.id)}}">Update</a>
    <button type="button" class="btn btn-danger" data-toggle='modal' data-target="#del_modal">Delete</button>
  </div>

  {% endif %}
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

        <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="post">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>


      </div>
    </div>
  </div>
</div>


{% endblock %}

projectKanpai/templates/create_post.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <form class="form-group" method="POST">
      {{form.hidden_tag()}}

      <div class="form-group">
        {{form.title.label(class="form-control-label")}}
        {{form.title(class="form-control form-control-lg")}}
      </div>
      <div class="form-group">
        {{form.text.label(class="form-control-label")}}
        {{form.text(class="form-control form-control-lg")}}
      </div>
      <div class="form-group">
        {{form.submit(class="btn btn-outline-info")}}
      </div>

    </form>
  </div>
{% endblock %}

projectKanpai/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class=" jumbotron">
    <div class="row">
      <div class="col-md-8">
        <h1>KP</h1>
        <p>Welcome to KP</p>
      </div>
      <div class="col-6 col-md-4">
        <h2> <a href="{{url_for('users.login')}}"> Log in </a></h2>
        <h3> or </h2>
        <h2> <a href="{{url_for('users.register')}}"> Register </a></h2>
      </div>
    </div>
  </div>



  <div class="container">

    {# Go through each blog post #}
    {% for post in blog_posts.items %}

    <div class="card" >
      <div class="card-body">
        <h2><a class="card-title" href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username)}}">Written By: {{ post.author.username }}</a>
        <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <div>
          {% if post in likePost %}
          <a href="{{ url_for('blog_posts.like_posts', blog_post_id = post.id, action = 'unlike')}}" type="button" class="btn btn-secondary" data-toggle='modal' data-target="#del_modal">unLike</a>
          {% else %}
            <a href="{{ url_for('blog_posts.like_posts', blog_post_id = post.id, action = 'like')}}" type="button" class="btn btn-danger" data-toggle='modal' data-target="#del_modal">Like</a>
          {% endif %}
        </div>
        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
      </div>
    </div>
   {% endfor %}

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
    </nav>




{% endblock %}

projectKanpai/templates/login.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}
    {{ form.password.label }} {{ form.password() }}
    {{ form.submit() }}
</form>
{% endblock %}

projectKanpai/templates/register.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}<br>
    {{ form.username.label }} {{ form.username() }}<br>
    {{ form.password.label }} {{ form.password() }}<br>
    {{ form.pass_confirm.label }} {{ form.pass_confirm() }}<br>
    {{ form.submit() }}
</form>
{% endblock %}

projectKanpai/templates/search.html
{% extends "base.html"%}
{% block content %}
<div class="jumbotron">
<h1> Please enter the keyword </h1>
<form method="POST">
    {{form.hidden_tag() }}
    {{form.key.label}} {{form.key}} {{form.submit()}}
</form>

{% if query %}
    <h3> there are {{query|length}} posts. </h3>
    <div class="card" >
        {% for post in query %}
        <div class="card-body">
        <h2><a class="card-title">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">
            Written By: {{ post.author.username }}</a>
        <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
        </div>  
        {% endfor %} 
    </div>
{% endif %}
{% endblock %}

projectKanpai/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1>Welcome to the page for {{user.username}}</h1>
    </div>
  </div>


{% for post in blog_posts.items  %}
  <h2> <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a> </h2>
  Written By: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a>
  <p class='text-muted'>post published on: {{post.date.strftime("%Y-%m-%d")}}</p>
   <br>
   <p>{{post.text}}</p>
   <br>
{% endfor %}
</div>

<nav aria-label='Page Navigation example'>
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)  %}
      {% if blog_posts.page == page_num %}
      <li class='page-item disabled'>
        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{ page_num}}</a>
      </li>
      {% else %}
      <li class='page-item'>
        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{ page_num}}</a>
      </li>
      {% endif %}
    {% endfor %}
  </ul>

</nav>




{% endblock %}